[package]
name = "bench"
version = "0.1.0"
edition = "2024"

[dependencies]
index = { path = "../index" }
facets = { path = ".." }
clap = { version = "4.5.53", features = ["derive"] }

[profile.release]
debug = true
